### ISSUE TITLE
FileNotFoundError, Costum data doesn't work. 

### ISSUE THREAD

**Issue by mherkhachatryan** [VachikKh/shared_budget#2]
When I run the code on my custom data, it gives **FileNotFoundError**. 
Entire error. 
```
python main.py -d /home/vachik/Downloads/budget.csv
Traceback (most recent call last):
  File "main.py", line 33, in <module>
    print(shared_budget("data.csv"))
  File "main.py", line 5, in shared_budget
    df = pd.read_csv(filename)
  File "/home/vachik/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 686, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/vachik/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 452, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/vachik/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 936, in __init__
    self._make_engine(self.engine)
  File "/home/vachik/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1168, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/vachik/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1998, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 361, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 653, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'
```
I reproduce my actions step by step, and a give possible solution to this.  

1. git clone in */home/vachik/mher/* directory. 
2. Create my data with name *budget.csv* in */home/vachik/Downloads/* directory. 
3. Run code `python main.py -d /home/vachik/Downloads/budget.csv` 
After these 3 simple steps, it brings this error mentioned above. 

**Possible source of error and solution** 
As I look in your source file, I see that you call `shared_budget` function with parameter `data.csv`, so you don't take the input parameter from the user, you should change the last call action, and give parameter user input.

**Comment by VachikKh** [comment]
Thanks, it is fixed now
